layout_disable.settings:
  type: config_object
  label: 'Layout-Disable Settings'
  mapping:
    disabled_layouts:
      type: sequence
      label: 'Disabled Layouts'
      sequence:
        type: string
        label: 'Disabled Layout'
